name: 构建

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: "清除缓存"
        required: false
        type: boolean
  push:
    branches:
      - ts_world

jobs:
  pre:
    runs-on: ubuntu-latest
    name: 预处理
    steps:
      - name: 初始化环境
        uses: actions/checkout@v3

      - name: 配置world
        run: |
          cd ./attic/world/
          sed -i '/roots.push_back/d' ./mkworld.cpp
          sed -i '/roots.back()/d' ./mkworld.cpp
          sed -i '85r world.txt' ./mkworld.cpp
          cat ./mkworld.cpp
          c++ -std=c++11 -I../.. -I.. -I../../ext -g -o mkworld ../../node/C25519.cpp ../../node/Salsa20.cpp ../../node/SHA512.cpp ../../node/Identity.cpp ../../node/Utils.cpp ../../node/InetAddress.cpp ../../osdep/OSUtils.cpp mkworld.cpp -lm

      - name: 生成 world
        run: |
          ./attic/world/mkworld > attic/world/world.c
          cp world.bin attic/world/planet
          sed -i '25,26d' node/Topology.cpp
          sed -i '23r attic/world/world.c' node/Topology.cpp
          cp node/Topology.cpp attic/world/world.cpp

      - name: 保存工作流产物
        uses: actions/upload-artifact@v3
        with:
          name: pre
          path: |
            node/Topology.cpp
            attic/world/
            world.*
          if-no-files-found: error
          retention-days: 1

  build-debian:
    runs-on: ubuntu-latest
    name: 构建 debian 安装源
    needs: [pre]
    steps:
      - name: 初始化环境
        uses: actions/checkout@v3

      - name: 下载工作流产物
        uses: actions/download-artifact@v3
        with:
          name: pre

      - name: 安装依赖
        run: |
          sudo apt-get install -y devscripts debhelper

      - name: 编译
        run: |
          make official

      - name: 打包
        run: |
          make debian
          ls -la
          mkdir dist
          cp ../zerotier-one* dist/

      # - name: 上传成果到 github actions
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: debian
      #     path: |
      #       world.*
      #       dist/
      #       zerotier-*
      #     if-no-files-found: error
      #     retention-days: 1
      
      - name: 准备签名密钥
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: 生成源
        run: |
          gpg -k
          mkdir -p apt-repo/dists/stable/main/{binary-all,binary-amd64,source}
          mkdir -p apt-repo/pool/main
          mkdir -p cache
          cp dist/*.deb apt-repo/pool/main
          apt-ftparchive generate .ts/apt-ftparchive.conf
          apt-ftparchive -c .ts/stable.conf release apt-repo/dists/stable > apt-repo/dists/stable/Release
          gpg --default-key "72BC9B25194091C6" --output apt-repo/dists/stable/Release.gpg -abs apt-repo/dists/stable/Release
          gpg --default-key "72BC9B25194091C6" --output apt-repo/dists/stable/InRelease --clearsign apt-repo/dists/stable/Release          
          gpg -a -o apt-repo/archive.key --export "72BC9B25194091C6"
          mkdir -p oss
          mv apt-repo oss/debian
          cp dist/ oss/debian/zt_world
          cp zerotier-* oss/debian/zt_world
          cp world.* oss/debian/zt_world
          cp .ts/index.html oss/

      - name: 发布源
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
          accessKeyId: ${{ secrets.OSS_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          bucket: tsde
          endpoint: oss-cn-chengdu.aliyuncs.com
          folder: oss


  build-controller:
    runs-on: ubuntu-latest
    name: 构建控制器
    needs: [pre]
    steps:
      - name: 初始化环境
        uses: actions/checkout@v3

      - name: 下载工作流产物
        uses: actions/download-artifact@v3
        with:
          name: pre

      - name: 获取参数
        id: pkw
        run: |
          echo "::set-output name=today::$(date +'%Y%m%d')"
          echo "::set-output name=git_branch::$(git name-rev --name-only HEAD)"

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v1

      - name: 设置 Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 登录阿里云容器
        uses: docker/login-action@v1
        with:
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: 调整镜像脚本
        run: |
          sed -i 's#registry.zerotier.com/zerotier#tossp#g' ./ext/central-controller-docker/Dockerfile

      - name: 构建镜像并推送
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ext/central-controller-docker/Dockerfile
          build-args: git_branch=${{ steps.pkw.outputs.git_branch }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            tossp/ztcentral-controller:latest
            tossp/ztcentral-controller:${{ steps.pkw.outputs.today }} 
            registry.cn-chengdu.aliyuncs.com/tossp/ztcentral-controller:latest
            registry.cn-chengdu.aliyuncs.com/tossp/ztcentral-controller:${{ steps.pkw.outputs.today }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  end:
    name: 结束
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build-debian, build-controller]
    steps:
      - name: 删除旧的工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
