name: 构建

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: "清除缓存"
        required: false
        type: boolean
  push:
    branches:
      - ts_world
    paths:
      - "ext/central-controller-docker/**"

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建控制器
    steps:
      - name: 初始化环境
        uses: actions/checkout@v3

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v1

      - name: 设置 Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 准备辅助镜像 controller-builder
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ext/central-controller-docker/Dockerfile.builder
          build-args: git_branch=${{ steps.pkw.outputs.git_branch }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: tossp/controller-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 准备辅助镜像 controller-run
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./ext/central-controller-docker/Dockerfile.run_base
          build-args: git_branch=${{ steps.pkw.outputs.git_branch }}
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: tossp/controller-run:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 删除旧的工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
